/// <reference types="vite/client" />

/**
 * vite-env.d.ts
 *
 * Purpose:
 * - Provides global TypeScript declarations for Vite-specific APIs:
 *   • import.meta.env (environment variables)
 *   • import.meta.hot (HMR)
 *   • Asset imports (.png, .svg, .vue, etc.)
 * - Allows declaring custom VITE_* environment variables with types.
 *
 * How to use:
 * - Do NOT edit this file unless you know TypeScript declaration syntax.
 * - To add custom env variables, extend the `ImportMetaEnv` interface:
 *
 *   interface ImportMetaEnv {
 *     readonly VITE_API_URL: string;
 *     readonly VITE_APP_TITLE: string;
 *   }
 *
 * - Ensure your .env*. files use only VITE_* prefixed variables.
 * - This file is automatically included by TypeScript and has no runtime effect.
 */

interface ImportMetaEnv {
  readonly VITE_SITE_URL?: string;
  readonly VITE_BASE_PATH?: string;
  readonly VITE_APP_NAME?: string;
  readonly VITE_APP_ENV?: "development" | "test" | "staging" | "production";
  readonly VITE_API_BASE_URL?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
